name: CommandSpyNC
authors: [Wild1145 / Ryan Wild]
version: 3.0
main: com.superiornetworks.commandviewer.CommandViewer
commands:
  cmdviewer:
    description: Toggles your command viewing ability on and off
    usage: <command>
